---
header-includes:
- \usepackage{amssymb}
- \usepackage{color}
- \documentclass{article}
- \usepackage{amsmath}
- \usepackage{setspace}
- \usepackage{xcolor}
- \usepackage{graphicx}
output:
pdf_document: newcommandault
html_document: newcommandault
---
\newcommand\T{{\top}}
\newcommand\ubeta{{\boldsymbol \beta}}
\newcommand\uSigma{{\boldsymbol \Sigma}}
\newcommand\uepsilon{{\boldsymbol \epsilon}}
\newcommand\umu{{\boldsymbol \mu}}
\newcommand\utheta{{\boldsymbol \theta}}
\newcommand\bg{{\boldsymbol \gamma}}
\newcommand\uphi{{\boldsymbol \phi}}
\newcommand\0{{\bf 0}}
\newcommand\uA{{\bf A}}
\newcommand\ua{{\bf a}}
\newcommand\uB{{\bf B}}
\newcommand\ub{{\bf b}}
\newcommand\uC{{\bf C}}
\newcommand\uD{{\bf D}}
\newcommand\uE{{\bf E}}
\newcommand\ue{{\bf e}}
\newcommand\uH{{\bf H}}
\newcommand\uI{{\bf I}}
\newcommand\uM{{\bf M}}
\newcommand\uQ{{\bf Q}}
\newcommand\uV{{\bf V}}
\newcommand\uX{{\bf X}}
\newcommand\ux{{\bf x}}
\newcommand\uY{{\bf Y}}
\newcommand\uy{{\bf y}}
\newcommand\uz{{\bf z}}
\newcommand\diag{{\rm diag}}

# Bayesian Reduced Rank Regression

## Introduction

In contemporary sociey, a big amount of data are generated and collected more easily and routinely in various academic and industrial areas, such as engineering, politics, B2C e-ccommerce, genomics, etc. Many problems could be cast into statistical problems under the framework of multivariate linear regression model, which is characterized by that both reponse variables and predictors are high dimensionality.

We assume $n$ independent observations of the response $\uy_i\in \mathcal{R}^q$ with predictor vector
$\ux_i\in\mathcal{R}^p$, $i=1,2,\ldots,n$. Cosider multivariate linear regression model as follows:
\begin{eqnarray}
	\uY=\uX\uC + \uE,
	(\#eq:eq1)
	\end{eqnarray}
where $\uY=(\uy_1,\uy_2,\ldots,\uy_n)^{\T}\in\mathcal{R}^{n\times q}$ is the response matrix, $\uX=(\ux_1,\ux_2,\ldots,\ux_n)^{\T}\in\mathcal{R}^{n\times p}$ is the design matrix, $\uC\in\mathcal{R}^{p\times q}$ is the coefficient matrix, and $\uE=(\ue_1,\ue_2,\ldots,\ue_n)^{\T}\in\mathcal{R}^{n\times q}$ is the disturbance matrix with $\ue_i$'s $\overset{iid}{\sim}\mathcal{N}_q(\0,\uSigma_e)$. We assume $\uSigma_e=\sigma^2\uI_q$. Therefore, we have $\uY\sim\mathcal{MN}(\uX\uC,\uSigma_e,\uI_n)$.

## Bayesian Rank Reduced Regression model

We consider to decompose the coefficient matrix into two part as follows:
\begin{eqnarray}
	 \uC=\uA\uB^{\T},
\end{eqnarray}
where $\uA\in\mathcal{R}^{p\times r}$, $\uB\in\mathcal{R}^{r\times q}$ and known $r\leq \min(p,q)$.
However, this decomposition is not unique, because with a $r\times r$ nonsingular matrix $\uQ, \uC=\uA\uB^{\T}=\uA\uQ\uQ^{-1}\uB^{\T}=\tilde{\uA}\tilde{\uB}^{\T}.$
In order to indentify it, we further decompose $\uA$. $\uA^{\T}=[\uI_r, {\uA^*}^{\T}]$. The author assumes that $p(\uA,\uB)\propto\exp\left(-\frac{\tau^2}{2} trace\{ \uA^{\T}\uA+\uB^{\T}\uB\}\right)$ and $\sigma^2\sim \mathcal{IG}(\frac{a}{2},\frac{b}{2})$.

### Posterior Distribution

Let $\tilde{\ua}_k$ and $\tilde{\ub}_k$ denote the $k$th column of $\uA$ and $\uB$, respectively. Let ${\ua}_j^{\T}$ and ${\ub}_l^{\T}$ denote the $y$th row of $\uA$ and $l$th row of $\uB$, respectively.

\begin{eqnarray*}
	&&p(\uY|\uA,\uB,\uSigma_e)\\
	&\propto& |\uSigma_e|^{-\frac{q}{2}}\exp\left(-\frac{1}{2}trace\{
	(\uY-\uX\uA\uB^{\T})(\uY-\uX\uA\uB^{\T})^{\T}\uSigma_e^{-1}\}\right)\\
	&=& (\sigma^2)^{-\frac{nq}{2}}\exp\left(-\frac{1}{2\sigma^2}trace\{
	(\uY-\uX\uA\uB^{\T})(\uY-\uX\uA\uB^{\T})^{\T}\}\right)\\
	&=&(\sigma^2)^{-\frac{nq}{2}}\exp\left(-\frac{1}{2\sigma^2}trace\{(\uY-\uX_{(\tilde{j})}\uA_{(j)}\uB^{\T})
	(\uY-\uX_{(\tilde{j})}\uA_{(j)}\uB^{\T})^{\T}\}\right)\\
	&\times&\exp\left(-\frac{1}{2\sigma^2}trace\{(\tilde{\ux}_j\ua_j^{\T}\uB^{\T}\uB\ua_j\tilde{\ux}_j^{\T})
	\}\right)\\
	&\times&\exp\left(\frac{1}{\sigma^2}trace\{(\tilde{\ux}_j\ua_j^{\T}\uB^{\T}(\uY-\uX_{(\tilde{j})}\uA_{(j)}
	\uB^{\T})^{\T})\}\right)\\
	&=&(\sigma^2)^{-\frac{nq}{2}}\exp\left(-\frac{1}{2\sigma^2}trace\{(\uY-\uX_{(\tilde{j})}\uA_{(j)}\uB^{\T})
	(\uY-\uX_{(\tilde{j})}\uA_{(j)}\uB^{\T})^{\T}\}\right)\\
	&\times&\exp\left(-\frac{1}{2\sigma^2}\ua_j^{\T}\uB^{\T}\uB\ua_j\tilde{\ux}_j^{\T}\tilde{\ux}_j\right)
	\times \exp\left((-2)\frac{-1}{2\sigma^2}\ua_j^{\T}\uB^{\T}(\uY-\uX_{(\tilde{j})}\uA_{(j)}
	\uB^{\T})^{\T}\tilde{\ux}_j\right).
\end{eqnarray*}

\begin{eqnarray*}
    &&p(\ua_j|\uA_{(j)},\uB,\uSigma_e,\uY)\\
    &\propto& p(\uA|\uB,\uSigma_e,\uY)\propto p(\uY|\uA,\uB,\uSigma_e)
    p(\uA,\uB)\\
    &\propto& p(\uY|\uA,\uB,\uSigma_e) \exp \left(-\frac{\tau^2}{2} trace\{ \uA^{\T}\uA+\uB^{\T}\uB\}\right)
    \\
    &\propto& p(\uY|\uA,\uB,\uSigma_e) \exp \left(-\frac{\tau^2}{2} \sum_{j=1}^{r}\ua_j^{\T}\ua_j\right)\\
    &\propto& \exp\left(-\frac{1}{2\sigma^2}\ua_j^{\T}\uB^{\T}\uB\ua_j\tilde{\ux}_j^{\T}\tilde{\ux}_j\right)
    \times \exp\left((-2)\frac{-1}{2\sigma^2}\ua_j^{\T}\uB^{\T}(\uY-\uX_{(\tilde{j})}\uA_{(j)}
    \uB^{\T})^{\T}\tilde{\ux}_j\right)\\
    &\times& \exp \left(-\frac{\tau^2}{2}\ua_j^{\T}\ua_j\right)\\
    &=& \exp\left\{-\frac{1}{2}\left(\ua_j^{\T}(\sigma^{-2}\uB^{\T}\uB\tilde{\ux}_j^{\T}\tilde{\ux}_j
    +\uI_r\tau^2)\ua_j-2\ua_j^{\T}\uB^{\T}(\uY-\uX_{(\tilde{j})}\uA_{(j)}
    \uB^{\T})^{\T}\tilde{\ux}_j\sigma^{-2}\right)\right\}\\
    &=& \exp\left\{-\frac{1}{2}\left(\ua_j^{\T}{\uSigma_j^{A}}^{-1}
    \ua_j-2\ua_j^{\T}{\uSigma_j^{A}}^{-1}{\uSigma_j^{A}}\uB^{\T}(\uY-\uX_{(\tilde{j})}\uA_{(j)}
    \uB^{\T})^{\T}\tilde{\ux}_j\sigma^{-2}\right)\right\}\\
    &=& \exp\left\{-\frac{1}{2}\left(\ua_j^{\T}{\uSigma_j^{A}}^{-1} \ua_j-2\ua_j^{\T}{\uSigma_j^{A}}^{-1}\umu_j^{A}\right)\right\}\\
    &\propto& \exp\left\{-\frac{1}{2}\left((\ua_j-\umu_j^{A})^{\T}{\uSigma_j^{A}}^{-1}(\ua_j-\umu_j^{A}) \right)\right\},
\end{eqnarray*}
where $\uSigma_j^{A}={(\uB^{\T}\uB\tilde{\ux}_j^{\T}\tilde{\ux}_j\sigma^{-2} +\uI_r\tau^2)}^{-1}$ and
$\umu_j^{A}={\uSigma_j^{A}}\uB^{\T}(\uY-\uX_{(\tilde{j})}\uA_{(j)} \uB^{\T})^{\T}\tilde{\ux}_j\sigma^{-2}$.

Hence, $\ua_j|\uA_{(j)},\uB,\uSigma_e,\uY \sim \mathcal{N}_r(\umu_j^A,\uSigma_j^A)$.
\begin{eqnarray*}
		&&p(\uY|\uA,\uB,\uSigma_e)\\
		&\propto& |\uSigma_e|^{-\frac{q}{2}}\exp\left(-\frac{1}{2}trace\{
		(\uY-\uX\uA\uB^{\T})^{\T}\uSigma_e^{-1}(\uY-\uX\uA\uB^{\T})\}\right)\\
		&=& (\sigma^2)^{-\frac{nq}{2}}\exp\left(-\frac{1}{2\sigma^2}trace\{
		(\uY-\uX\uA\uB^{\T})^{\T}(\uY-\uX\uA\uB^{\T})\}\right)\\
		&=&(\sigma^2)^{-\frac{nq}{2}}\exp\left(-\frac{1}{2\sigma^2}trace\{(\uY_{(\tilde{l})}
		-\uX\uA(\uB^{\T})_{(\tilde{l})})^{\T}(\uY_{(\tilde{l})}-\uX\uA(\uB^{\T})_{(\tilde{l})})\}\right)\\
		&\times& \exp\left(-\frac{1}{2\sigma^2}\left[\ub_{l}^{\T} (\uX\uA)^{\T}\uX\uA\ub_{l}-
		2\ub_{l}^{\T}(\uX\uA)^{\T}\tilde{\uy}_l+\tilde{\uy}_l^{\T}\tilde{\uy}_l\right]\right).
\end{eqnarray*}

\begin{eqnarray*}
		&&p(\ub_l|\uA,(\uB^{\T})_{(\tilde{l})},\uY,\uSigma_e)\\
		&\propto& p(\uB|\uA,\uY,\uSigma_e)
		\propto p(\uY|\uA,\uB,\uSigma_e)p(\uA,\uB)\\
		&\propto & p(\uY|\uA,\uB,\uSigma_e) \exp \left(-\frac{\tau^2}{2} trace\{ \uA^{\T}\uA+\uB^{\T}\uB\}\right) \\
		&\propto& p(\uY|\uA,\uB,\uSigma_e) \exp \left(-\frac{\tau^2}{2} \sum_{l=1}^{r}\ub_l^{\T}\ub_l\right)\\
		&\propto& \exp\left(-\frac{1}{2\sigma^2}\left[\ub_{l}^{\T} (\uX\uA)^{\T}\uX\uA\ub_{l}-
		2\ub_{l}^{\T}(\uX\uA)^{\T}\tilde{\uy}_l+\tilde{\uy}_l^{\T}\tilde{\uy}_l\right]\right)
		\exp \left(-\frac{\tau^2}{2}\ub_l^{\T}\ub_l\right)\\
		&=& \exp\left(-\frac{1}{2}\left[\ub_{l}^{\T} (\uX\uA)^{\T}\uX\uA\ub_{l}\sigma^{-2}-
		2\ub_{l}^{\T}(\uX\uA)^{\T}\tilde{\uy}_l\sigma^{-2}+
		\tilde{\uy}_l^{\T}\tilde{\uy}_l\sigma^{-2}\right]\right)
		\exp \left(-\frac{\tau^2}{2}\ub_l^{\T}\ub_l\right)\\
		&=& \exp\left\{-\frac{1}{2}\left(\ub_{l}^{\T}( (\uX\uA)^{\T}\uX\uA\sigma^{-2}+\uI_r\tau^2)\ub_{l}-
		2\ub_{l}^{\T}(\uX\uA)^{\T}\tilde{\uy}_l\sigma^{-2}\right)\right\}\\
		&=& \exp\left\{-\frac{1}{2}\left(\ub_{l}^{\T}{\uSigma_j^B}^{-1}\ub_{l}-
		2\ub_{l}^{\T}{\uSigma_j^B}^{-1}{\uSigma_j^B}(\uX\uA)^{\T}\tilde{\uy}_l\sigma^{-2}\right)\right\}\\
		&=& \exp\left\{-\frac {1}{2}\left(\ub_{l}^{\T}{\uSigma_j^B}^{-1}\ub_{l}-
		2\ub_{l}^{\T}{\uSigma_j^B}^{-1}\umu_j^B\right)\right\}\\
		&\propto& \exp\left\{-\frac{1}{2}\left((\ub_{l}-\umu_j^B)^{\T}{\uSigma_j^B}^{-1}(\ub_{l}-\umu_j^B)
		\right)\right\},
\end{eqnarray*}
where $\uSigma_j^B= ((\uX\uA)^{\T}\uX\uA\sigma^{-2}+\uI_r\tau^2)^{-1}$ and $\umu_j^B={\uSigma_j^B}(\uX\uA)^{\T}\tilde{\uy}_l\sigma^{-2}$.

Hence, $\ub_l|\uA,(\uB^{\T})_{(\tilde{l})},\uY,\uSigma_e\sim \mathcal{N}_r(\umu_j^B,\uSigma_j^B)$.

We know that the element in $k$th row and $k$th column of $\uSigma_e$ is $\sigma^2, k=1,2,\ldots,q$.
\begin{eqnarray*}
 &&p(\sigma^2|\uA,\uB,\uY,(\uSigma_e)_{(k)(\tilde{k})})\\
 &\propto& p(\uSigma_e|\uA,\uB,\uY)\propto
 p(\uY|\uA,\uB,\uSigma_e)p(\uSigma_e)\propto p(\uY|\uA,\uB,\uSigma_e)p(\sigma^2)\\
 &=& (\sigma^2)^{-\frac{nq}{2}}\exp\left(-\frac{1}{2\sigma^2}trace\{
 (\uY-\uX\uA\uB^{\T})(\uY-\uX\uA\uB^{\T})^{\T}\}\right)\\
 &\times & (\sigma^2)^{-\frac{a}{2}-1}\exp\left(-\frac{b}{2\sigma^2}\right)\\
 &=& (\sigma^2)^{-\frac{nq+a}{2}-1}\exp\left(-\frac{1}{2\sigma^2}(trace\{
 (\uY-\uX\uA\uB^{\T})(\uY-\uX\uA\uB^{\T})^{\T}\}+b)\right).
\end{eqnarray*}
Hence, $\sigma^2|\uA,\uB,\uY,(\uSigma_e)_{(k)(\tilde{k})}\sim \mathcal{IG}\left(\frac{nq+a}{2},\frac{1}{2}(trace\{(\uY-\uX\uA\uB^{\T})(\uY-\uX\uA\uB^{\T})^{\T}\}+b)\right)$.

### Gibbs Sampling

The algorithm is easy to construct. Begin with initial values $\uA^{(0)}, \uSigma^{(0)}$, then for t = 1,2,...

- Step (1) Given $\uA_{(j)}^{(t-1)},\uB^{\T(t-1)}, {\sigma^2}^{(t-1)}$, draw $\ua_j^{(t)}$ from
	$\mathcal{N}_r(\umu_j^A,\uSigma_j^A),j=r+1,r+2,\ldots,p$;
- Step (2) Given $\uA^{(t)},\uB^{\T(t-1)}_{(\tilde{l})}, {\sigma^2}^{(t-1)}$, draw $\ub_l^{(t)}$ from
	$\mathcal{N}_r(\umu_j^B,\uSigma_j^B),l=1,2,\ldots,q$;
- Step (3) Given $\uB^{(t)}, \uA^{(t)}$, draw ${\sigma^2}^{(t)}$ from $\mathcal{IG}\left(a^*,b^*\right)$.
- Step (4) Repeat step (1) to step (3) until convergence.


Note that, the step (1) samples the $\ua_j$ from $j=r+1$, because first part of $\uA$ is $\uI_r$, which is
known. Hence, step (1) samples the $\uA^*$ and then insert $\uI_r$ together to construct $\uA$.

## Model Selection

To this point we have proceeded as if r were known. In most applications this will not be
true and so analysis to this point is conditional.When r is unknown, the analysis may be carried out for several alternative values of r.  Under the Bayesian framework, model selection can be implemented by using the model posterior probability conditioning the data,
\[
	p(M_r|y)=\frac{p(y|M_r)p(M_r)}{\sum_{r\in \mathcal{M}}p(y|M_r)p(M_r)}=
	\frac{p(y|M_r)}{\sum_{r\in \mathcal{M}}p(y|M_r)},
\]
where $\mathcal{M}={1,2,\ldots,min(p,q)}$, and $p(M_r)=\frac{1}{card(\mathcal{M})}$.

Hence, as the prior of rank(model) is flat, $p(M_r|y)$ is only determined by marginal likelihood ($p(y|M_r)$). The model selection problem here is then converted to find out the rank which maximizes the marginal likelihood ($p(y|M_r)$). In order to calculate the $p(y|M_r)$, I used Laplace and Gelfand and Dey (GD) methods, and then compare with DIC.

### Laplace

Let $\utheta  = (\uA,\uB,\sigma^2)$
\begin{eqnarray*}
		p(\uY|M_r) &=& \int \int \int p(\uY|\utheta,M)p(\utheta) d{\uA}d{\uB}d{\sigma^2}\\
		&\approx& p(\uY|\hat{\utheta},M)p(\hat\utheta|M)|(nq)^{-1}\hat\uSigma_M|^{1/2} (2\pi)^{(k_M/2)},
\end{eqnarray*}
where $(\hat\uA,\hat\uB,\hat\sigma^2)=\arg \max p(\uY|{\uA},{\uB},{\sigma^2},M)p(\uA,\uB,\sigma^2|M)$.

Hence,
\begin{eqnarray}
&&\log p(\uY|M_r) \nonumber\\
&\approx& \log p(\uY|\hat{\utheta},M) + \log p(\hat\utheta|M) -\frac{1}{2}k_M\log nq +\frac{1}{2}|\uSigma_M|
+ \frac{k_M}{2}\log 2\pi\nonumber\\
&=&-\frac{1}{2} \left(-2\log(p(\uY|\hat{\uA},\hat{\uB},\hat{\sigma^2},M)) + k_M \log nq\right)  +C\nonumber\\
&=&-\frac{1}{2}(nq\log(2\pi\hat{\sigma^2})-
\frac{1}{2\hat{\sigma^2}} trace\left\{(\uY-\uX\hat\uC)^{\T}(\uY-\uX\hat\uC) \right\} \nonumber\\
&&+ [r(p+q-r)+1] \log(nq))+C\nonumber\\
&=& -\frac{1}{2}BIC + C\nonumber\\
&=& -\frac{1}{2}BIC, \text{as } n\rightarrow \infty.
(\#eq:eq3)
\end{eqnarray}

The problem we are facing when we use Laplace here is that we need to find the mode of $p(\uA,\uB,\sigma^2|\uY)$, in which $(\uA,\uB,\sigma^2)$ is high-dimensional. To address this problem, Besag proposed an iterated conditional modes (ICM) algorithm. The ICM obtains the local maximum of the joint posterior by iteratively maximizing the full conditionals as follows:


- Begin with initial values $\uA^{(0)},\uSigma^{(0)}$, then for t = 1,2,...
- Given $\uA_{(j)}^{(t-1)},\uB^{\T(t-1)}, {\sigma^2}^{(t-1)}$, $\ua_j^{(t)}\leftarrow\umu_j^A,j=r+1,r+2,\ldots,p$;
- Given $\uA^{(t)},\uB^{\T(t-1)}_{(\tilde{l})}, {\sigma^2}^{(t-1)}$, $\ub_l^{(t)}\leftarrow\umu_j^B,l=1,2,\ldots,q$;
- Given $\uB^{(t)}, \uA^{(t)}$, ${\sigma^2}^{(t)}\leftarrow\frac{b^*}{a^*-1}$.

We obtain $\uC^{(t)}=\uA^{(t)}\uB^{\T(t)}$ and estimate $\hat{\uC}_{ICM}=T^{-1}\sum_{t=1}^{T}\uC^{(t)}$. Put the $\hat{\uC}_{ICM}$ in the Eq.\@ref(eq:eq3) to calculate $-\frac{1}{2}BIC$. Hence, the Laplace here is actually propotional to BIC.  

###  DIC

Let $\utheta=(\uA,\uB,\sigma^2)$,
\begin{eqnarray*}
	&&D(\utheta)\\
	&=&-2\log p(\uY|\utheta,M) \\
	&=&nq\log(2\pi\sigma^2)+ \frac{1}{\sigma^2} trace\left\{(\uY-\uX\uC)^{\T}(\uY-\uX\uC) \right\}
\end{eqnarray*}

Then DIC can be computed by
\[
DIC \approx 2T^{-1}\sum_{t=1}^{T}D(\utheta^{(t)})-D(T^{-1}\sum_{t=1}^{T}\utheta^{(t)}),
\]
where $\utheta^{(t)}$ is a MCMC sample generated from $p(\utheta|\uY)$.

Note that $DIC=D(\bar{\utheta})+2P_D$, which is analogous to AIC.

### Gelfand \& Dey (GD)

Let $\utheta=(\uA,\uB,\sigma^2)$,then the GD estimator is $$p(\uY|M)\approx\left[T^{-1}\sum_{t=1}^{T}\frac{g(\utheta^{(t)})}{p(\uY|\utheta^{(t)})p(\utheta^{(t)})}\right]^{-1},$$
where $\utheta^{(t)}$ is a MCMC sample generated from $p(\utheta|\uY)$. Define $g(\utheta)=N(\utheta|\tilde{\utheta},\tilde{\uSigma})$, where $\tilde{\utheta}$ and $\tilde{\uSigma}$ are MCMC sample mean and variance, respectively.
I use formular as follows:
\begin{eqnarray}
\log p(\uY|M)&\approx& \log \left[\frac{1}{T}\sum_{t=1}^{T}\frac{g^{(t)}}{f^{(t)}}\right]^{-1}\nonumber\\
&=&\log \left[\frac{T}{\sum_{t=1}^{T}\frac{g^{(t)}}{f^{(t)}}}\right]\nonumber\\
&=&\log T - \log \left(\sum_{t=1}^{T}\frac{g^{(t)}}{f^{(t)}}\right)\nonumber\\
&=&\log T - \log \left(\sum_{t=1}^{T}\exp (\log g^{(t)}-\log f^{(t)})\right)(\#eq:4)\\
&=&\log T - \log \left(\sum_{t=1}^{T}\exp c_t\right)\nonumber\\
&=&\log T - \log \left(e^{ c_{1} }e^{\sum_{t=1}^{T} (c_t-c_{1})}\right)\nonumber\\
&=&\log T - \left[c_1 + \log \left(\sum_{t=2}^{T} (c_t-c_{1})\right)\right]\nonumber,
\end{eqnarray}
where $g^{(t)}=g(\utheta), f^{(t)}=p(\uY|\utheta^{(t)})p(\utheta^{(t)}), c_t = \log g^{(t)}-\log f^{(t)}$.

Note that when calculating $\log p(\uY|M)$, there is a computation problem in formula \@ref(eq:4),
$\exp (\log g^{(t)}-\log f^{(t)})$ goes to infinity, due to a very large magnitude of
$\log g^{(t)}-\log f^{(t)}$. To solve this problem, I used
$\log T - \left[c_1 + \log \left(\sum_{t=2}^{T} (c_t-c_{1})\right)\right]$ to calculate $\log p(\uY|M)$.

## Simulation Study

### Data Generation
In the simulation study, my goal is to find out the true model or true rank of coefficient matrix($\uC$) based on Laplace, DIC and GD method. I set $n=100,q=12,p=7$ and $\sigma^2=2$. The coefficient matrix is as follows:

$$\uC=\left[ \begin{array}{@{}*{12}{c}@{}}
1 & 0 & 0 & 2 & -1 & 0  & 0 & 0 & 0  & 0 & 1  & -1\\
0 & 1 & 0 & 0 & 0  & -3 & 2 & 0 & 0  & 0 & -1 & 3\\
0 & 0 & 1 & 0 & 0  & 0  & 0 & 3 & -3 & 4 & 2  & 2\\
1 & 0 & 0 & 2 & -1 & 0  & 0 & 0 & 0  & 0 & 1  & -1\\
0 & 1 & 0 & 0 & 0  & -3 & 2 & 0 & 0  & 0 & -1 & 3\\
0 & 1 & 0 & 0 & 0  & -3 & 2 & 0 & 0  & 0 & -1 & 3\\
0 & 0 & 1 & 0 & 0  & 0  & 0 & 3 &-3  &4  & 2  & 2
\end{array} \right]$$
Hence, the true rank of $\uC$ is 3.

Generate data based on the model from Eq.\@ref(eq:eq1). For the prior,
$p(\uA,\uB)\propto\exp\left(-\frac{\tau^2}{2} trace\{ \uA^{\T}\uA+\uB^{\T}\uB\}\right)$ and $\sigma^2\sim \mathcal{IG}(\frac{a}{2},\frac{b}{2})$, where $\tau=10^{-3}$ and $a=b=1$.

After running the MCMC simulation, the result based on 1 replication is shown in Table \@ref(tab:table1).

Table: (\#tab:table1) Model Selection among Laplace, DIC and GD Based on 1 Replication.

|Method($\log$) | 1 | 2|**3**|  4  |  5  | 6 | 7 |
|:-----:|:----:|:----:|:-----:|:----:|:---:|:----:|:---:|
|Laplace  | -3007 |-2535 |**-2223** |-2257 |-2285 |-2310 |-2329|
|DIC |84300 |17779|**7302**|  7317|  7325|  7363|  7405|
|GD|-3062 |-2631| **-2347**| -2397| -2436| -2470| -2495|
|MSE |1.032 |0.186 |**0.0120** |0.014 |0.0170| 0.0192| 0.0217|

The MSE in the table is defined as follows:
\[
MSE = \frac{trace\{(\hat \uC -\uC)^{\T}(\hat \uC -\uC)\}}{pq}.
\]
MSE indicates the goodness of fit in the reduced rank regression model. We can observe that the MSE is minimized when the rank is 3. This demonstrates that parameter estimation is good enough. For the Laplace, DIC and GD method, in this case, all of them select the true rank. Given rank$(\uC)=3$, the estimated $\uC$ is as follows:

|||||||||||||
|:---:|:-----:|:----:|:----:|:-----:|:-----:|:----:|:----:|:----:|:----:|:----:|:----:|
|1.07 | 0.17  | 0.01 | 2.34 | -0.89 | -0.12 | -0.11| -0.08| -0.07| 0.03 | 1.26 | -1.10|
|-0.02| 1.00  | 0.04 | -0.14| -0.17 | -2.83 | 2.10 | 0.10 | 0.03 | 0.03 | -1.04| 3.17 |
|0.13 | -0.03 | 0.99 | 0.18 | -0.02 | 0.08  | 0.00 | 3.06 | -2.85| 4.03 | 2.10 | 2.06 |
|0.94 | 0.14  | 0.03 | 2.05 | -0.78 | -0.08 | -0.11| -0.03| -0.10| 0.07 | 1.13 | -0.95|
|0.04 | 0.99  | 0.04 | -0.00| -0.21 | -2.79 | 2.05 | 0.10 | 0.01 | 0.04 | -0.95| 3.05 |
|0.12 | 1.05  | 0.00 | 0.18 | -0.29 | -2.93 | 2.14 | -0.02| 0.12 | -0.12| -0.98| 3.03 |
|0.08 | -0.01 | 0.98 | 0.08 | 0.01  | 0.03  | 0.04 | 3.03 | -2.81| 3.98 | 2.01 | 2.14 |

In addition, when selected rank is larger than 3, the MSE is not worse than I expect. In
other words, the model based on larger model (larger rank in $\uC$), the overfiteed models still have a good
estimation for the $\uC$. The values of DIC, Laplace and GD are not far away from the value at true rank.
This is very reasonable for overfitted model. But when selected rank smaller than true rank,
the MSE increase significantly, and the corresponding values of DIC, Laplace and GD are far away from the value at true rank. This means the model miss some important variables. The analysis is based on one replication.

In Table \@ref(tab:table2), the result is based on 1000 replication. I want to see the perfermance of methods for model selection. In
Table \@ref(tab:table2), Laplace and GD always select true rank, however, the DIC tends to select larger model, because the average of
 selected rank in DIC is about 3.5, whereas, that of Laplace and GD are 3. Besides, for the successful probability of selecting true
  rank, the Laplace and GD, of course, is 100\%, but is 61.7\% for DIC. This makes sense because Laplace and GD are approximated and exact calculation for marginal likehihood, respectively. They work well in model fitting. The DIC is analogous to AIC, which tends to select larger model and better for short-term prediction.

Table: (\#tab:table2) Comparison among Laplace, DIC, GD Based on 1000 Replication.

| Method  | Mean of Selected rank   | Selection Probabiliy  |
|:-------:|:-----------------------:|:---------------------:|
|Laplace  | 3                       |1                    |
|DIC      | 3.525                   |0.617                |
|GD       | 3                       |1                    |

### R Code for Bayeian reduced rank regression with DIC used in the simulation study

```{r, eval = FALSE}
library(mvtnorm)
library(invgamma)
rm(list=ls())
## Data & Model##
row1 <- c(1,0,0,2,-1,0,0,0,0,0,1,-1)
row2 <- c(0,1,0,0,0,-3,2,0,0,0,-1,3)
row3 <- c(0,0,1,0,0,0,0,3,-3,4,2,2)
C <- rbind(row1,row2,row3,row1,row2,row2,row3)
true.rank <- 3
p <- dim(C)[1]
q <- dim(C)[2]
true.sig2 <- 2
true.SIGe <- diag(true.sig2,q)
n=100
a=b=1
tau2=1e-3
MC.size=5000
burn_in=3000
reptn <- 125
error <- array(NA,dim = c(reptn,p))
DIC <- array(NA,dim = c(reptn,p))
TPR.DIC <- rep(NA,reptn)
TPR.error <- rep(NA,reptn)
hat.rank <- rep(NA,reptn)
v=0
for (i in 1:reptn) {
  t1=Sys.time()
  set.seed(2144+i+125*v)
  X <- matrix(rnorm(n*p,0,1),n,p)
  E <- rmvnorm(n, rep(0,q), true.SIGe, method="chol")
  Y=X%*%C+E
  ## Reduced Rank Regression model ##
  for (r in 1:p) {
    Hat.A <- array(NA,dim = c(p,r,MC.size))
    Hat.B <- array(NA,dim = c(q,r,MC.size))
    Hat.C <- array(NA,dim = c(p,q,MC.size))
    Hat.sig2 <- rep(NA,MC.size)
    # initial values
    hat.C <- coef(lm(Y~X-1))
    if (r==1){
      hat.B <- as.matrix(hat.C[1:r,])
    } else {
      hat.B <- t(hat.C[1:r,])
    }
    if (r==p) {
      hat.A <- diag(1,r)
    } else {
      hat.A <- rbind(diag(1,r),hat.C[(r+1):p,]%*%hat.B%*%solve(crossprod(hat.B)))
    }

    hat.sig2 <- mean(diag(tcrossprod(Y-X%*%hat.A%*%t(hat.B))))  #true.sig2
    ## MCMC ##
    for (jin in 1:MC.size) {
      # Sampling A
      if (r==p){
        Hat.A[,,jin] <- hat.A
      } else {
        for(j in (r+1):p) {
          Sig.A_j <- solve(crossprod(hat.B)*as.numeric(crossprod(X[,j]))/hat.sig2+diag(tau2,r))
          mu.A_j <- Sig.A_j%*%t(hat.B)%*%t(Y-X[,-j]%*%hat.A[-j,]%*%t(hat.B))%*%X[,j]/hat.sig2
          hat.a_j <- rmvnorm(n=1,mean = mu.A_j,sigma = Sig.A_j)
          hat.A[j,] <- hat.a_j
        }
        Hat.A[,,jin] <- hat.A
      }
      # Sampling B
      Sig.B_l <- solve(crossprod(X%*%hat.A)/hat.sig2+diag(tau2,r))
      for(l in 1:q) {
        mu.B_l <- Sig.B_l%*%t(X%*%hat.A)%*%Y[,l]/hat.sig2
        hat.b_l <- t(rmvnorm(n=1,mean = mu.B_l,sigma = Sig.B_l))
        hat.B[l,] <- t(hat.b_l)
      }
      Hat.B[,,jin] <- hat.B
      Hat.C[,,jin] <- hat.A%*%t(hat.B)
      #Sampling Sig2
      hat.sig2 <- rinvgamma(n = 1,shape = (q*n+a)/2,rate = 0.5*(b+sum(diag(tcrossprod(Y-X%*%hat.A%*%t(hat.B))))))
      Hat.sig2[jin] <- hat.sig2
      #print(jin)
    }
    hat.C <- apply(Hat.C[,,-(1:burn_in)],c(1,2),mean)
    hat.sig2 <- mean(Hat.sig2[-(1:burn_in)])
    # print(C)
    D.theta <- rep(NA,MC.size-burn_in)
    j=0
    for (jin in (burn_in+1):MC.size) {
      j=j+1
      D.theta[j] <- n*q*log(2*pi*Hat.sig2[jin])+Hat.sig2[jin]*sum(diag(crossprod(Y-X%*%Hat.C[,,jin])))
    }
    D.hat.theta <- n*q*log(2*pi*hat.sig2)+hat.sig2*sum(diag(crossprod(Y-X%*%hat.C)))
    DIC[i,r] <- 2*mean(D.theta)- D.hat.theta
    error[i,r] <- sum((hat.C-C)^2)/(p*q)
  }
  hat.rank[i] <- which.min(DIC[i,])
  TPR.DIC[i] <- hat.rank[i]==true.rank
  TPR.error[i] <- which.min(error[i,])==true.rank
  print(c(i,hat.rank[i]))
  print(Sys.time()-t1)
}

data.frame(hat.rank=mean(hat.rank),TPR.DIC=mean(TPR.DIC),TPR.ERR=mean(TPR.error))
save(list = ls(), file = paste0('DIC-',v,'.RData'))
```
